@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":EstateMateParser" as EstateMateParser LOGIC_COLOR
participant ":DeleteTenantCommandParser" as DeleteTenantCommandParser LOGIC_COLOR
participant "d:DeleteTenantCommand" as DeleteTenantCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> EstateMateParser : parseCommand("dtenant 1")
activate EstateMateParser

create DeleteTenantCommandParser
EstateMateParser -> DeleteTenantCommandParser
activate DeleteTenantCommandParser

DeleteTenantCommandParser --> EstateMateParser
deactivate DeleteTenantCommandParser

EstateMateParser -> DeleteTenantCommandParser : parse("1")
activate DeleteTenantCommandParser

create DeleteTenantCommand
DeleteTenantCommandParser -> DeleteTenantCommand
activate DeleteTenantCommand

DeleteTenantCommand --> DeleteTenantCommandParser :
deactivate DeleteTenantCommand

DeleteTenantCommandParser --> EstateMateParser : d
deactivate DeleteTenantCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteTenantCommandParser -[hidden]-> EstateMateParser
destroy DeleteTenantCommandParser

EstateMateParser --> LogicManager : d
deactivate EstateMateParser

LogicManager -> DeleteTenantCommand : execute(m)
activate DeleteTenantCommand

DeleteTenantCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteTenantCommand
deactivate Model

create CommandResult
DeleteTenantCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteTenantCommand
deactivate CommandResult

DeleteTenantCommand --> LogicManager : r
deactivate DeleteTenantCommand

[<--LogicManager
deactivate LogicManager
@enduml
