@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "EstateMate Storage" #F4F6F6{
Class "<<interface>>\nEstateMateStorage" as EstateMateStorage
Class JsonEstateMateStorage
Class JsonSerializableEstateMate
Class JsonAdaptedPerson
Class JsonAdaptedJob
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" EstateMateStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> EstateMateStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonEstateMateStorage .up.|> EstateMateStorage
JsonEstateMateStorage ..> JsonSerializableEstateMate
JsonSerializableEstateMate --> "*" JsonAdaptedPerson
JsonSerializableEstateMate --> "*" JsonAdaptedJob
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
